file-version: 1
vendor: OneLang
name: Yaml
version: 0.1
languages:
  - id: python
    native-dependencies:
      - { name: PyYAML, version: 5.3.1 }
  - id: java
    native-dependencies:
      - { name: org.yaml:snakeyaml, version: 1.27 }
  - id: csharp
    native-dependencies:
      - { name: YamlDotNet, version: 8.1.0 }
