name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npx tsc -b . test build
    - run: npx ./test/lib/ProjectTest.js
    - run: npx ./test/lib/SelfTest.js
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - run: ls -al
    - run: ls -al
      working-directory: ./test/artifacts/ProjectTest/OneLang/Python
    - run: python main.py
      working-directory: ./test/artifacts/ProjectTest/OneLang/Python
